---
- hosts: all
  become: true
  tasks: 

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    ansible.builtin.apt:
      name: 
        - apache2
        - name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  

  - name: update repository index
    ansible.builtin.yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package
    ansible.builtin.yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  
